### ISSUE TITLE
Support `Float32` and other precisions

### ISSUE THREAD

**Issue by yebai** [compintell/Mooncake.jl#196]
The assumption of only supporting `Float64` is too strong. Are there any good reasons? 

I am labelling this as bugs to signal its priority.

**Comment by willtebbutt** [comment]
The reason is a lack of testing infrastructure which can properly handle `Float32` -- with multiple precisions involved, it becomes a little bit more tricky to properly determine appropriate accuracy thresholds for finite differencing etc.

I've removed the `bug` label, in favour of `enhancement` + `high priority`, because `bug` isn't an accurate description of what's going on here.

**Comment by willtebbutt** [comment]
@yebai and @red-portal discovered that we're going to need a rule to `Core.Intrinsics.fptrunc` is going to need a conversion rule + a rule -- see https://github.com/TuringLang/AdvancedVI.jl/pull/71

**Comment by willtebbutt** [comment]
I think I'd rather just provide an informative error message, in order to avoid users thinking they're testing one thing, but actually testing another -- I can easily imagine a situation in which a user accidentally has a `Float64` somewhere in their input, and then the whole thing gets silently promoted to `Float64`, and then they're testing something other than what they meant to test.

**Comment by willtebbutt** [comment]
@penelopeysm discovered in https://github.com/TuringLang/docs/pull/559#discussion_r1857551478 that Mooncake's current rule for matrix-matrix multiplication in LuxLib doesn't successfully handle the case that the two input arrays contain numbers at different precisions.

It really shouldn't be too hard to handle this properly -- we would just need to re-write the current from_rrule implementations of the various variants of matrix-matrix multiplication found around [here](https://github.com/compintell/Mooncake.jl/blob/d9a695279742a35203bf23f7190df97643e9bd57/ext/MooncakeLuxLibExt.jl#L10-L18) to have proper Mooncake rules which

    define is_primitive for arrays whose elements are subtypes of IEEEFloat, and
    define the rrule!s in such a way that ensures the correct element-type is adhered to.
    add a method of rrule!! which is a catch-all for all other element types, which always errors with some kind of sensible error message that users can make use of to know how to modify their code.

Note: this is also a great opportunity to ensure excellent performance in Lux.jl -- the current implementations of the rules involve more allocations than are really needed, because we do not increment the gradients in-place.

**Comment by willtebbutt** [comment]
I'm marking this as done, because I believe it to basically be done. We can re-open if there is a reason to.

**Comment by willtebbutt** [comment]
It seems to be fine for `Float32` and `Float64`
